package services.menu;

import entities.Employee;
import resource.ScannerManager;
import services.dashboards.FinanceDashboardService;

import java.util.Scanner;

/**
 * Manages the menu for finance dashboard operations.
 * Author: Aashika Vachhani
 */
public class FinanceDashboardMenu {

    /**
     * Displays the menu options for the finance dashboard.
     */
    public static void displayMenu() {
        System.out.println("Finance Dashboard Menu:");
        System.out.println("1. Revenue within a specific time period");
        System.out.println("2. Revenue generated by a particular car");
        System.out.println("3. Revenue generated by a particular customer");
        System.out.println("4. Main Menu");
        System.out.println("5. Exit");
    }

    /**
     * Retrieves the user's choice from the menu.
     *
     * @return The user's choice.
     */
    public static int getUserChoice() {
        int choice = 0;
        Scanner scanner = ScannerManager.getScanner();
        boolean validInput = false;
        while (!validInput) {
            System.out.print("Enter your choice: ");
            if (scanner.hasNextInt()) {
                choice = scanner.nextInt();
                validInput = true;
            } else {
                System.out.println("Invalid input. Please enter a number.");
                scanner.next(); // Clear the invalid input
            }
        }
        return choice;
    }

    /**
     * Handles the menu options for the finance dashboard.
     *
     * @param employee The logged-in employee.
     */
    public static void handleMenu(Employee employee) {
        boolean validChoice = false;

        while (!validChoice) {
            displayMenu();
            int choice = getUserChoice();

            switch (choice) {
                case 1:
                    FinanceDashboardService.displayFinanceReportForDateRange();
                    MainMenu.handleManagerMenu(employee);
                    validChoice = true;
                    break;
                case 2:
                    FinanceDashboardService.displayFinanceReportForCar();
                    MainMenu.handleManagerMenu(employee);
                    validChoice = true;
                    break;
                case 3:
                    FinanceDashboardService.displayFinanceReportForCustomer();
                    MainMenu.handleManagerMenu(employee);
                    validChoice = true;
                    break;
                case 4:
                    MainMenu.handleManagerMenu(employee);
                    validChoice = true;
                    break;
                case 5:
                    MainMenu.exitApplication();
                    break;
                default:
                    System.out.println("Invalid choice. Please try again.");
                    break;
            }
        }
    }

}
